### ISSUE TITLE
SFOS 2.1.4.13: app crashes after selecting another list

### ISSUE THREAD

**Issue by schmittlauch** [Armadill0/harbour-tasklist#88]
Since upgrading to SailfishOS 2.1.4.13, tasklist crashes when selecting another task-list than the default one from the list of task-lists.
This doesn't happen with a frashe profile though (having deleted `~/.local/share/harbour-tasklist`), so this may be hard to debug.

As this particular update contains a Qt update to 5.6.3 this may be the thing to blame.

```
$ harbour-tasklist
[D] unknown:0 - Using Wayland-EGL
[W] unknown:0 - Could not find any zN.M subdirs!
[W] unknown:0 - Theme dir "/usr/share/themes/jolla-ambient/meegotouch/z1.0/" does not exist
*** Error in `harbour-tasklist': double free or corruption (fasttop): 0x48f2de20 ***
Aborted
```

**Comment by Armadill0** [comment]
I'll try to debug that. I also have a problem to scroll down lists which crashs the app. Maybe it can simply be solved by a new build as the latest already is quite old.

**Comment by schmittlauch** [comment]
I just rebuild the master branch in a 2.1.4.13 SDK, but that didn't fix the issue.

**Comment by schmittlauch** [comment]
Looks like valgrind could be useful for finding the cause of crashing (I'd need to repeat this with debugsymbols of course):

```
==26572== Thread 1:
==26572== Invalid read of size 4
==26572==    at 0x541D52C: QVariant::QVariant(QString const&) (in /usr/lib/libQt5Core.so.5.6.3)
==26572==  Address 0xa062d00 is 0 bytes inside a block of size 26 free'd
==26572==    at 0x4840B28: free (vg_replace_malloc.c:530)
==26572==    by 0x4F3F3CB: ??? (in /usr/lib/libQt5Qml.so.5.6.3)
==26572==  Block was alloc'd at
==26572==    at 0x483F3EC: malloc (vg_replace_malloc.c:299)
==26572==    by 0x52C9155: QArrayData::allocate(unsigned int, unsigned int, unsigned int, QFlags<QArrayData::AllocationOption>) (in /usr/lib/libQt5Core.so.5.6.3)
==26572== 
==26572== Invalid read of size 4
==26572==    at 0x5423916: ??? (in /usr/lib/libQt5Core.so.5.6.3)
==26572==  Address 0xa062d00 is 0 bytes inside a block of size 26 free'd
==26572==    at 0x4840B28: free (vg_replace_malloc.c:530)
==26572==    by 0x4F3F3CB: ??? (in /usr/lib/libQt5Qml.so.5.6.3)
==26572==  Block was alloc'd at
==26572==    at 0x483F3EC: malloc (vg_replace_malloc.c:299)
==26572==    by 0x52C9155: QArrayData::allocate(unsigned int, unsigned int, unsigned int, QFlags<QArrayData::AllocationOption>) (in /usr/lib/libQt5Core.so.5.6.3)
==26572== 
==26572== Invalid read of size 4
==26572==    at 0x5423374: ??? (in /usr/lib/libQt5Core.so.5.6.3)
==26572==  Address 0xa062d00 is 0 bytes inside a block of size 26 free'd
==26572==    at 0x4840B28: free (vg_replace_malloc.c:530)
==26572==    by 0x4F3F3CB: ??? (in /usr/lib/libQt5Qml.so.5.6.3)
==26572==  Block was alloc'd at
==26572==    at 0x483F3EC: malloc (vg_replace_malloc.c:299)
==26572==    by 0x52C9155: QArrayData::allocate(unsigned int, unsigned int, unsigned int, QFlags<QArrayData::AllocationOption>) (in /usr/lib/libQt5Core.so.5.6.3)
==26572== 
==26572== Invalid free() / delete / delete[] / realloc()
==26572==    at 0x4840B28: free (vg_replace_malloc.c:530)
==26572==    by 0x54233A1: ??? (in /usr/lib/libQt5Core.so.5.6.3)
==26572==  Address 0xa062d00 is 0 bytes inside a block of size 26 free'd
==26572==    at 0x4840B28: free (vg_replace_malloc.c:530)
==26572==    by 0x4F3F3CB: ??? (in /usr/lib/libQt5Qml.so.5.6.3)
==26572==  Block was alloc'd at
==26572==    at 0x483F3EC: malloc (vg_replace_malloc.c:299)
==26572==    by 0x52C9155: QArrayData::allocate(unsigned int, unsigned int, unsigned int, QFlags<QArrayData::AllocationOption>) (in /usr/lib/libQt5Core.so.5.6.3)
==26572== 
pure virtual method called
terminate called without an active exception
==26572== 
==26572== Process terminating with default action of signal 6 (SIGABRT)
==26572==    at 0x5732BF6: __libc_do_syscall (libc-do-syscall.S:44)
==26572==    by 0x5742DCD: raise (raise.c:56)
==26572==    by 0x5745C57: abort (abort.c:89)
==26572==    by 0x562670B: __gnu_cxx::__verbose_terminate_handler() (in /usr/lib/libstdc++.so.6.0.19)
==26572== 
```

**Comment by schmittlauch** [comment]
I'm not really familiar with Qt and C++, but it really looks like the bug is not in the harbour-tasklist code but in the QML backend handling the memory allocation for the ListModel.
 
valgrind output:
```
==21680== Invalid free() / delete / delete[] / realloc()
==21680==    at 0x4840B28: free (vg_replace_malloc.c:530)
==21680==    by 0x54233A1: deallocate (qarraydata.h:222)
==21680==    by 0x54233A1: ~QString (qstring.h:1066)
==21680==    by 0x54233A1: v_clear<QString> (qvariant_p.h:169)
==21680==    by 0x54233A1: FilteredDestructor (qvariant_p.h:413)
==21680==    by 0x54233A1: delegate<QString> (qvariant_p.h:439)
==21680==    by 0x54233A1: switcher<void, QVariantDestructor<(anonymous namespace)::CoreTypesFilter> > (qmetatypeswitcher_p.h:68)
==21680==    by 0x54233A1: (anonymous namespace)::clear(QVariant::Private*) (qvariant.cpp:123)
==21680==    by 0x541D23D: QVariant::~QVariant() (qvariant.cpp:1376)
==21680==    by 0x54214B9: QVariant::cmp(QVariant const&) const (qvariant.cpp:3508)
==21680==    by 0x503B833: operator== (qvariant.h:431)
==21680==    by 0x503B833: QQmlOpenMetaObject::setValue(QByteArray const&, QVariant const&) (qqmlopenmetaobject.cpp:346)
==21680==    by 0x50BCFCB: setValue (qqmllistmodel_p_p.h:146)
==21680==    by 0x50BCFCB: ModelNodeMetaObject::updateValues() (qqmllistmodel.cpp:1277)
==21680==    by 0x50BDC19: ModelNodeMetaObject::initialize() (qqmllistmodel.cpp:1240)
==21680==    by 0x50BDC87: ModelNodeMetaObject::toDynamicMetaObject(QObject*) (qqmllistmodel.cpp:1252)
==21680==    by 0x540F845: QObjectData::dynamicMetaObject() const (qobject.cpp:195)
==21680==    by 0x503FE23: disconnect (qqmlnotifier_p.h:202)
==21680==    by 0x503FE23: QQmlData::disconnectNotifiers() (qqmlengine.cpp:1614)
==21680==    by 0x50400A7: QQmlData::destroyed(QObject*) (qqmlengine.cpp:1710)
==21680==    by 0x5415C2F: QObject::~QObject() (qobject.cpp:922)
==21680==  Address 0x9f7e2f0 is 0 bytes inside a block of size 26 free'd
==21680==    at 0x4840B28: free (vg_replace_malloc.c:530)
==21680==    by 0x4F3F3CB: deallocate (qarraydata.h:222)
==21680==    by 0x4F3F3CB: deallocate (qstring.h:1066)
==21680==    by 0x4F3F3CB: QString::~QString() (qstring.h:1066)
==21680==    by 0x50BDFC7: ListElement::destroy(ListLayout*) (qqmllistmodel.cpp:1095)
==21680==    by 0x50BE049: ListModel::clear() (qqmllistmodel.cpp:558)
==21680==    by 0x50BE3B1: QQmlListModel::clear() (qqmllistmodel.cpp:2055)
==21680==    by 0x50D0EBF: QQmlListModel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (moc_qqmllistmodel_p.cpp:123)
==21680==    by 0x50D1007: QQmlListModel::qt_metacall(QMetaObject::Call, int, void**) (moc_qqmllistmodel_p.cpp:210)
==21680==    by 0x507124B: QQmlObjectOrGadget::metacall(QMetaObject::Call, int, void**) const (qqmlpropertycache.cpp:1571)
==21680==    by 0x502119F: CallMethod(QQmlObjectOrGadget const&, int, int, int, int*, QV4::ExecutionEngine*, QV4::CallData*) (qv4qobjectwrapper.cpp:1156)
==21680==    by 0x5021707: CallPrecise(QQmlObjectOrGadget const&, QQmlPropertyData const&, QV4::ExecutionEngine*, QV4::CallData*) (qv4qobjectwrapper.cpp:1393)
==21680==    by 0x5021F41: QV4::QObjectMethod::callInternal(QV4::CallData*) const (qv4qobjectwrapper.cpp:1871)
==21680==    by 0x5031E7B: call (qv4object_p.h:334)
==21680==    by 0x5031E7B: QV4::Runtime::callProperty(QV4::ExecutionEngine*, int, QV4::CallData*) (qv4runtime.cpp:998)
==21680==  Block was alloc'd at
==21680==    at 0x483F3EC: malloc (vg_replace_malloc.c:299)
==21680==    by 0x52C9155: QArrayData::allocate(unsigned int, unsigned int, unsigned int, QFlags<QArrayData::AllocationOption>) (qarraydata.cpp:108)
==21680==    by 0x5316905: allocate (qarraydata.h:216)
==21680==    by 0x5316905: QString::QString(QChar const*, int) (qstring.cpp:1517)
==21680==    by 0x98A4923: QSQLiteResultPrivate::fetchNext(QVector<QVariant>&, int, bool) (qsql_sqlite.cpp:302)
==21680==    by 0x98A4F19: QSQLiteResult::exec() (qsql_sqlite.cpp:483)
==21680==    by 0xA3294DD: QSqlQuery::exec() (in /usr/lib/libQt5Sql.so.5.6.3)
==21680== 
==21680== Invalid read of size 4
==21680==    at 0x5423916: load (atomic_base.h:496)
==21680==    by 0x5423916: load<int> (qatomic_cxx11.h:96)
==21680==    by 0x5423916: load (qbasicatomic.h:119)
==21680==    by 0x5423916: ref (qrefcount.h:49)
==21680==    by 0x5423916: QString (qstring.h:890)
==21680==    by 0x5423916: v_construct_helper<QString> (qvariant_p.h:117)
==21680==    by 0x5423916: v_construct<QString> (qvariant_p.h:146)
==21680==    by 0x5423916: v_construct<QString> (qvariant_p.h:154)
==21680==    by 0x5423916: FilteredConstructor (qvariant_p.h:354)
==21680==    by 0x5423916: delegate<QString> (qvariant_p.h:375)
==21680==    by 0x5423916: switcher<void, QVariantConstructor<(anonymous namespace)::CoreTypesFilter> > (qmetatypeswitcher_p.h:68)
==21680==    by 0x5423916: (anonymous namespace)::construct(QVariant::Private*, void const*) (qvariant.cpp:117)
==21680==    by 0x541F679: QVariant::operator=(QVariant const&) (qvariant.cpp:1892)
==21680==    by 0x503B7B7: QQmlOpenMetaObject::setValue(QByteArray const&, QVariant const&) (qqmlopenmetaobject.cpp:349)
==21680==    by 0x50BCFCB: setValue (qqmllistmodel_p_p.h:146)
==21680==    by 0x50BCFCB: ModelNodeMetaObject::updateValues() (qqmllistmodel.cpp:1277)
==21680==    by 0x50BDC19: ModelNodeMetaObject::initialize() (qqmllistmodel.cpp:1240)
==21680==    by 0x50BDC87: ModelNodeMetaObject::toDynamicMetaObject(QObject*) (qqmllistmodel.cpp:1252)
==21680==    by 0x540F845: QObjectData::dynamicMetaObject() const (qobject.cpp:195)
==21680==    by 0x503FE23: disconnect (qqmlnotifier_p.h:202)
==21680==    by 0x503FE23: QQmlData::disconnectNotifiers() (qqmlengine.cpp:1614)
==21680==    by 0x50400A7: QQmlData::destroyed(QObject*) (qqmlengine.cpp:1710)
==21680==    by 0x5415C2F: QObject::~QObject() (qobject.cpp:922)
==21680==    by 0x5416087: QObject::~QObject() (qobject.cpp:1042)
==21680==    by 0x50BDF8B: ListElement::destroy(ListLayout*) (qqmllistmodel.cpp:1134)
==21680==  Address 0x9f7e2f0 is 0 bytes inside a block of size 26 free'd
==21680==    at 0x4840B28: free (vg_replace_malloc.c:530)
==21680==    by 0x4F3F3CB: deallocate (qarraydata.h:222)
==21680==    by 0x4F3F3CB: deallocate (qstring.h:1066)
==21680==    by 0x4F3F3CB: QString::~QString() (qstring.h:1066)
==21680==    by 0x50BDFC7: ListElement::destroy(ListLayout*) (qqmllistmodel.cpp:1095)
==21680==    by 0x50BE049: ListModel::clear() (qqmllistmodel.cpp:558)
==21680==    by 0x50BE3B1: QQmlListModel::clear() (qqmllistmodel.cpp:2055)
==21680==    by 0x50D0EBF: QQmlListModel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (moc_qqmllistmodel_p.cpp:123)
==21680==    by 0x50D1007: QQmlListModel::qt_metacall(QMetaObject::Call, int, void**) (moc_qqmllistmodel_p.cpp:210)
==21680==    by 0x507124B: QQmlObjectOrGadget::metacall(QMetaObject::Call, int, void**) const (qqmlpropertycache.cpp:1571)
==21680==    by 0x502119F: CallMethod(QQmlObjectOrGadget const&, int, int, int, int*, QV4::ExecutionEngine*, QV4::CallData*) (qv4qobjectwrapper.cpp:1156)
==21680==    by 0x5021707: CallPrecise(QQmlObjectOrGadget const&, QQmlPropertyData const&, QV4::ExecutionEngine*, QV4::CallData*) (qv4qobjectwrapper.cpp:1393)
==21680==    by 0x5021F41: QV4::QObjectMethod::callInternal(QV4::CallData*) const (qv4qobjectwrapper.cpp:1871)
==21680==    by 0x5031E7B: call (qv4object_p.h:334)
==21680==    by 0x5031E7B: QV4::Runtime::callProperty(QV4::ExecutionEngine*, int, QV4::CallData*) (qv4runtime.cpp:998)
==21680==  Block was alloc'd at
==21680==    at 0x483F3EC: malloc (vg_replace_malloc.c:299)
==21680==    by 0x52C9155: QArrayData::allocate(unsigned int, unsigned int, unsigned int, QFlags<QArrayData::AllocationOption>) (qarraydata.cpp:108)
==21680==    by 0x5316905: allocate (qarraydata.h:216)
==21680==    by 0x5316905: QString::QString(QChar const*, int) (qstring.cpp:1517)
==21680==    by 0x98A4923: QSQLiteResultPrivate::fetchNext(QVector<QVariant>&, int, bool) (qsql_sqlite.cpp:302)
==21680==    by 0x98A4F19: QSQLiteResult::exec() (qsql_sqlite.cpp:483)
==21680==    by 0xA3294DD: QSqlQuery::exec() (in /usr/lib/libQt5Sql.so.5.6.3)
==21680== 
==21680== Invalid read of size 4
==21680==    at 0x5423374: load (atomic_base.h:496)
==21680==    by 0x5423374: load<int> (qatomic_cxx11.h:96)
==21680==    by 0x5423374: load (qbasicatomic.h:119)
==21680==    by 0x5423374: deref (qrefcount.h:60)
==21680==    by 0x5423374: ~QString (qstring.h:1066)
==21680==    by 0x5423374: v_clear<QString> (qvariant_p.h:169)
==21680==    by 0x5423374: FilteredDestructor (qvariant_p.h:413)
==21680==    by 0x5423374: delegate<QString> (qvariant_p.h:439)
==21680==    by 0x5423374: switcher<void, QVariantDestructor<(anonymous namespace)::CoreTypesFilter> > (qmetatypeswitcher_p.h:68)
==21680==    by 0x5423374: (anonymous namespace)::clear(QVariant::Private*) (qvariant.cpp:123)
==21680==    by 0x541D23D: QVariant::~QVariant() (qvariant.cpp:1376)
==21680==    by 0x50BCFD1: ModelNodeMetaObject::updateValues() (qqmllistmodel.cpp:1276)
==21680==    by 0x50BDC19: ModelNodeMetaObject::initialize() (qqmllistmodel.cpp:1240)
==21680==    by 0x50BDC87: ModelNodeMetaObject::toDynamicMetaObject(QObject*) (qqmllistmodel.cpp:1252)
==21680==    by 0x540F845: QObjectData::dynamicMetaObject() const (qobject.cpp:195)
==21680==    by 0x503FE23: disconnect (qqmlnotifier_p.h:202)
==21680==    by 0x503FE23: QQmlData::disconnectNotifiers() (qqmlengine.cpp:1614)
==21680==    by 0x50400A7: QQmlData::destroyed(QObject*) (qqmlengine.cpp:1710)
==21680==    by 0x5415C2F: QObject::~QObject() (qobject.cpp:922)
==21680==    by 0x5416087: QObject::~QObject() (qobject.cpp:1042)
==21680==    by 0x50BDF8B: ListElement::destroy(ListLayout*) (qqmllistmodel.cpp:1134)
==21680==    by 0x50BE049: ListModel::clear() (qqmllistmodel.cpp:558)
==21680==  Address 0x9f7e2f0 is 0 bytes inside a block of size 26 free'd
==21680==    at 0x4840B28: free (vg_replace_malloc.c:530)
==21680==    by 0x4F3F3CB: deallocate (qarraydata.h:222)
==21680==    by 0x4F3F3CB: deallocate (qstring.h:1066)
==21680==    by 0x4F3F3CB: QString::~QString() (qstring.h:1066)
==21680==    by 0x50BDFC7: ListElement::destroy(ListLayout*) (qqmllistmodel.cpp:1095)
==21680==    by 0x50BE049: ListModel::clear() (qqmllistmodel.cpp:558)
==21680==    by 0x50BE3B1: QQmlListModel::clear() (qqmllistmodel.cpp:2055)
==21680==    by 0x50D0EBF: QQmlListModel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (moc_qqmllistmodel_p.cpp:123)
==21680==    by 0x50D1007: QQmlListModel::qt_metacall(QMetaObject::Call, int, void**) (moc_qqmllistmodel_p.cpp:210)
==21680==    by 0x507124B: QQmlObjectOrGadget::metacall(QMetaObject::Call, int, void**) const (qqmlpropertycache.cpp:1571)
==21680==    by 0x502119F: CallMethod(QQmlObjectOrGadget const&, int, int, int, int*, QV4::ExecutionEngine*, QV4::CallData*) (qv4qobjectwrapper.cpp:1156)
==21680==    by 0x5021707: CallPrecise(QQmlObjectOrGadget const&, QQmlPropertyData const&, QV4::ExecutionEngine*, QV4::CallData*) (qv4qobjectwrapper.cpp:1393)
==21680==    by 0x5021F41: QV4::QObjectMethod::callInternal(QV4::CallData*) const (qv4qobjectwrapper.cpp:1871)
==21680==    by 0x5031E7B: call (qv4object_p.h:334)
==21680==    by 0x5031E7B: QV4::Runtime::callProperty(QV4::ExecutionEngine*, int, QV4::CallData*) (qv4runtime.cpp:998)
==21680==  Block was alloc'd at
==21680==    at 0x483F3EC: malloc (vg_replace_malloc.c:299)
==21680==    by 0x52C9155: QArrayData::allocate(unsigned int, unsigned int, unsigned int, QFlags<QArrayData::AllocationOption>) (qarraydata.cpp:108)
==21680==    by 0x5316905: allocate (qarraydata.h:216)
==21680==    by 0x5316905: QString::QString(QChar const*, int) (qstring.cpp:1517)
==21680==    by 0x98A4923: QSQLiteResultPrivate::fetchNext(QVector<QVariant>&, int, bool) (qsql_sqlite.cpp:302)
==21680==    by 0x98A4F19: QSQLiteResult::exec() (qsql_sqlite.cpp:483)
==21680==    by 0xA3294DD: QSqlQuery::exec() (in /usr/lib/libQt5Sql.so.5.6.3)
==21680== 
==21680== Invalid free() / delete / delete[] / realloc()
==21680==    at 0x4840B28: free (vg_replace_malloc.c:530)
==21680==    by 0x54233A1: deallocate (qarraydata.h:222)
==21680==    by 0x54233A1: ~QString (qstring.h:1066)
==21680==    by 0x54233A1: v_clear<QString> (qvariant_p.h:169)
==21680==    by 0x54233A1: FilteredDestructor (qvariant_p.h:413)
==21680==    by 0x54233A1: delegate<QString> (qvariant_p.h:439)
==21680==    by 0x54233A1: switcher<void, QVariantDestructor<(anonymous namespace)::CoreTypesFilter> > (qmetatypeswitcher_p.h:68)
==21680==    by 0x54233A1: (anonymous namespace)::clear(QVariant::Private*) (qvariant.cpp:123)
==21680==    by 0x541D23D: QVariant::~QVariant() (qvariant.cpp:1376)
==21680==    by 0x50BCFD1: ModelNodeMetaObject::updateValues() (qqmllistmodel.cpp:1276)
==21680==    by 0x50BDC19: ModelNodeMetaObject::initialize() (qqmllistmodel.cpp:1240)
==21680==    by 0x50BDC87: ModelNodeMetaObject::toDynamicMetaObject(QObject*) (qqmllistmodel.cpp:1252)
==21680==    by 0x540F845: QObjectData::dynamicMetaObject() const (qobject.cpp:195)
==21680==    by 0x503FE23: disconnect (qqmlnotifier_p.h:202)
==21680==    by 0x503FE23: QQmlData::disconnectNotifiers() (qqmlengine.cpp:1614)
==21680==    by 0x50400A7: QQmlData::destroyed(QObject*) (qqmlengine.cpp:1710)
==21680==    by 0x5415C2F: QObject::~QObject() (qobject.cpp:922)
==21680==    by 0x5416087: QObject::~QObject() (qobject.cpp:1042)
==21680==    by 0x50BDF8B: ListElement::destroy(ListLayout*) (qqmllistmodel.cpp:1134)
==21680==  Address 0x9f7e2f0 is 0 bytes inside a block of size 26 free'd
==21680==    at 0x4840B28: free (vg_replace_malloc.c:530)
==21680==    by 0x4F3F3CB: deallocate (qarraydata.h:222)
==21680==    by 0x4F3F3CB: deallocate (qstring.h:1066)
==21680==    by 0x4F3F3CB: QString::~QString() (qstring.h:1066)
==21680==    by 0x50BDFC7: ListElement::destroy(ListLayout*) (qqmllistmodel.cpp:1095)
==21680==    by 0x50BE049: ListModel::clear() (qqmllistmodel.cpp:558)
==21680==    by 0x50BE3B1: QQmlListModel::clear() (qqmllistmodel.cpp:2055)
==21680==    by 0x50D0EBF: QQmlListModel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (moc_qqmllistmodel_p.cpp:123)
==21680==    by 0x50D1007: QQmlListModel::qt_metacall(QMetaObject::Call, int, void**) (moc_qqmllistmodel_p.cpp:210)
==21680==    by 0x507124B: QQmlObjectOrGadget::metacall(QMetaObject::Call, int, void**) const (qqmlpropertycache.cpp:1571)
==21680==    by 0x502119F: CallMethod(QQmlObjectOrGadget const&, int, int, int, int*, QV4::ExecutionEngine*, QV4::CallData*) (qv4qobjectwrapper.cpp:1156)
==21680==    by 0x5021707: CallPrecise(QQmlObjectOrGadget const&, QQmlPropertyData const&, QV4::ExecutionEngine*, QV4::CallData*) (qv4qobjectwrapper.cpp:1393)
==21680==    by 0x5021F41: QV4::QObjectMethod::callInternal(QV4::CallData*) const (qv4qobjectwrapper.cpp:1871)
==21680==    by 0x5031E7B: call (qv4object_p.h:334)
==21680==    by 0x5031E7B: QV4::Runtime::callProperty(QV4::ExecutionEngine*, int, QV4::CallData*) (qv4runtime.cpp:998)
==21680==  Block was alloc'd at
==21680==    at 0x483F3EC: malloc (vg_replace_malloc.c:299)
==21680==    by 0x52C9155: QArrayData::allocate(unsigned int, unsigned int, unsigned int, QFlags<QArrayData::AllocationOption>) (qarraydata.cpp:108)
==21680==    by 0x5316905: allocate (qarraydata.h:216)
==21680==    by 0x5316905: QString::QString(QChar const*, int) (qstring.cpp:1517)
==21680==    by 0x98A4923: QSQLiteResultPrivate::fetchNext(QVector<QVariant>&, int, bool) (qsql_sqlite.cpp:302)
==21680==    by 0x98A4F19: QSQLiteResult::exec() (qsql_sqlite.cpp:483)
==21680==    by 0xA3294DD: QSqlQuery::exec() (in /usr/lib/libQt5Sql.so.5.6.3)
```

**Comment by schmittlauch** [comment]
I'm going to use this issue to collect al relevant log related to this crash:

When running the app with QML debug enabled:
```
[W] unknown:501 - file:///usr/share/harbour-tasklist/qml/pages/TaskPage.qml:501: TypeError: Cannot read property of null
[W] unknown:499 - file:///usr/share/harbour-tasklist/qml/pages/TaskPage.qml:499: TypeError: Cannot read property of null
*** Error in `/usr/bin/harbour-tasklist': double free or corruption (fasttop): 0x4d52d480 ***
```

**Comment by schmittlauch** [comment]
When stepping through the QML code I found out that the app crashes on line 92 of TaskPage.qml when invoking `taskListModel.clear()`. But this doesn't happen everytime, this function is invoked already multiple times when launching the app while it doesn't crash then.

**Comment by popanz** [comment]
The problem only appears on longer lists. If you have a list with more than 40 items. It allways crashes.

**Comment by schmittlauch** [comment]
> If you have a list with more than 40 items, it allways crashes.

I can't confirm that, as my workaround so far was exporting the lists as a backup on SailfishOS 2.1.3.x (in this case in the emulator), delete `~/.local/share/harbour-tasklist` and import the backup again on 2.1.4.13 .
My longest list has 318 entries but no crashes so far.

So it seems to depend on the Qt version the database was written with.

**Comment by schmittlauch** [comment]
Turns out the export-import workaround stopped working after some days and the app is crashing again. Though it's not crashing on line 91 anymore, it's hard to find the exact location.
After switching to another list, scrolling it is still possible for ~1sec before it crashes then.

**Comment by pmaier1** [comment]
Will you be able to fix this? Tasklist is one of my most used apps on SFOS and there's no good equivalent to my knowledge. Would of course donate for getting the app working again!

**Comment by sargo-devel** [comment]
Hi!
I hope i fixed this issue. See my pull request: https://github.com/Armadill0/harbour-tasklist/pull/89.
I have tested it on Xperia X with SFOS 2.1.4.14. It works fine, no crashes at all!

**Comment by pmaier1** [comment]
Yeah, so awesome! Nice to see progress here :+1:

**Comment by Armadill0** [comment]
Alright, I released a new version to fix this issue: https://github.com/Armadill0/harbour-tasklist/releases/tag/1.8.13

Harbour release is in QA.

Thanks to @sargo-devel and @schmittlauch for debugging and fixing the issue! :+1: :smile:

**Comment by schmittlauch** [comment]
Just for the record: The root cause for that bug was indeed a QTBUG: https://bugreports.qt.io/browse/QTBUG-61261

So if we ever reach Qt >= 5.9.2 we could remove the workaround for that crash – or maybe just leave it there.
